# Generated by Django 5.0.1 on 2024-03-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RedditDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=50)),
                ('thumbnail', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField()),
                ('media_type', models.CharField(max_length=10)),
                ('redditor', models.CharField(max_length=50)),
                ('subreddit_name', models.CharField(max_length=100)),
                ('comments_count', models.PositiveIntegerField()),
                ('score', models.IntegerField()),
                ('content_url', models.URLField()),
                ('hyperlink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50)),
                ('thumbnail', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('channel_image', models.URLField()),
                ('channel_name', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('upload_date', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
                ('view_count', models.CharField(max_length=50)),
                ('like_count', models.CharField(max_length=50)),
                ('player', models.TextField()),
            ],
        ),
    ]
